# Usa una imagen base oficial de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el código de la aplicación
COPY . .

# Compila la aplicación Next.js
RUN npm run build

# Expone el puerto en el que la aplicación correrá
EXPOSE 4000

# Comando para correr la aplicación en modo producción
CMD ["npm", "start"]
